# Meta Daten
url: https://elematic.at # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Elematic Webdesign
description: Webdesign aus Wien
version: v0.1
lang: de-AT

copyright: © 2024 - Elematic.at

# E-Mails
email: info@elematic.at

# Firma
company-name: Elematic Webdesign
company-address: 
company-city: Wien
company-country: Österreich
company-fn: FN xxxxx s
company-uid: ATUxxxxxxxx

# Social Media
x-url: 
github-url: https://github.com/blackmaker07/
facebook-url: 
instagram-url:

# Google
google-tag:
google-analytics:

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Sass
sass:
  style: compressed
  load_paths:
    - _sass
    - vendor/bundle/ruby/3.2.0/gems/bootstrap-5.3.2/assets/stylesheets/bootstrap

# HTML Compress
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []