baseURL = 'https://blackmaker07.github.io/'
languageCode = 'de-AT'
title = 'My New Hugo Site'

# Navigation

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'Kontakt'
pageRef = '/kontakt'
weight = 40

[[menus.main]]
name = 'Impressum'
pageRef = '/impressum'
weight = 50

[[menus.main]]
name = 'Datenschutz'
pageRef = '/datenschutz'
weight = 60


# Module

[module]

[module.hugoVersion]
extended = false
min = "0.116.0"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
target = "assets/js/bootstrap.bundle.min.js"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "node_modules/bootstrap-icons/font/fonts"
target = "static/css/fonts"